Add API endoints, serializers, router for telegram user processing
Studio-Yandex-Practicum/you_can_bot pull request #11
Opened 2023-08-19 11:21 UTC by melax08

Добавил три ручки относящихся к сущности пользователя:
- ViewSet состоящий из миксинов для реализации конкретных типов запросов (Retrieve, Create, Partial Update);
- Два сериализатора, один подходит для создания информации о ТГ пользователе и для получения детальной информации по указанному telegram_id, а второй подходит для частичного обновления информации, в соответствии с задачей это: name и surname;
- Роутер для API, в который включены ручки users;

Возник вопрос по полю "telegram_username" модели "UserFromTelegram":
Пользователь телеграм может без проблем менять свой username на уровне telegram.
Гипотетическая проблема, которая может из этого следовать: У юзера 1 был никнейм: "Vasya", он зарегался в боте, в БД у нас сохранился telegram_username = Vasya.

Позже, юзер 1 решил поменять свой ник в телеге на другой, а еще позже, появился юзер 2, который решил занять username Vasya, после чего, решил зарегаться в боте you can. Юзер 2 столкнется с проблемой, что его username уже занят у нас в боте. Хоть проблема крайне маловероятная, но в горизонте нескольких лет с ней кто-то может столкнуться. 

Самый простой вариант решения проблемы: отказаться от Unique=True для поля telegram_username модели UserFromTelegram.

2023-08-24 09:30 UTC, melax08 commented
Добавил тесты по эндпоинтам относящимся к юзеру

2023-08-24 11:36 UTC, TomatoInOil requested changes

2023-08-24 11:36 UTC, TomatoInOil commented on src/backend/api/views.py
> +        print(self.action)
Забыл убрать print()

2023-08-24 11:36 UTC, TomatoInOil commented on src/backend/api/views.py
> +    serializer_class = UserFromTelegramRetrieveCreateSerializer
Ты определил метод def get_serializer_class(self):, явно указав там Сериализаторы, поэтому строку с serializer_class = UserFromTelegramRetrieveCreateSerializer можно удалить

2023-08-24 16:16 UTC, melax08 commented on src/backend/api/views.py
> +        print(self.action)
Исправил.

2023-08-24 16:16 UTC, melax08 commented on src/backend/api/views.py
> +    serializer_class = UserFromTelegramRetrieveCreateSerializer
Удалил.

2023-08-25 20:20 UTC, TomatoInOil approved these changes

2023-08-25 20:21 UTC, merged