Feature/api endpoints answer
Studio-Yandex-Practicum/you_can_bot pull request #13
Opened 2023-08-21 08:08 UTC by olegtsss

Подготовил ручку. Запрос:

```
POST http://127.0.0.1:8000/api/v1/users/1234565/tasks/1/answers/
Content-Type: application/json

{
    "number": "1",
    "content": "б"
}
```

Создается новая запись в таблице Answer. Если уже ответ был дан ранее, то он будет перезаписан. Измняется поле `current_question` в связанной таблице TastStatus, но только, если текущее значение меньше присланного.

2023-08-21 11:01 UTC, TomatoInOil requested changes
Забыл прописать в описании к задаче: нужно также написать тесты для этой ручки

2023-08-21 11:47 UTC, olegtsss commented on src/backend/api/views.py
> +        return Response(status=status.HTTP_404_NOT_FOUND)
Сделано.

2023-08-21 11:54 UTC, olegtsss commented on src/backend/api/views.py
> +    number = int(request.data.get('number'))
Обработано!

2023-08-21 12:05 UTC, olegtsss commented on src/backend/api/views.py
> +    answers = Answer.objects.filter(task=task_number, number=number)
Сделано!

2023-08-21 12:10 UTC, olegtsss commented on src/backend/api/views.py
> +        serializer = AnswerSerializer(answers.first(), data=request.data, partial=True)
Сделано!

2023-08-23 00:48 UTC, olegtsss commented on src/backend/api/views.py
> +    return Response(status=status.HTTP_400_BAD_REQUEST)
Сделано!

2023-08-24 09:48 UTC, TomatoInOil requested changes

2023-08-24 09:48 UTC, TomatoInOil commented on src/backend/api/tests/test_case.py
> +    ANSWER_5 = {'number': 1}
Чем отличается ANSWER_2 от ANSWER_3? 
Если есть ANSWER_1, то должен быть и {"number": "first", "content": "a"} для проверки на BAD_REQUEST

2023-08-24 09:48 UTC, TomatoInOil commented on src/backend/api/tests/test_urls.py
> +        self.assertEqual(response.data['content'], self.ANSWER_2['content'])
В ANSWER_2 number уже имеет тип int

2023-08-24 15:38 UTC, olegtsss commented on src/backend/api/tests/test_case.py
> +    URL_ANSWER_CREATE = '/api/v1/users/{telegram_id}/tasks/{task_number}/answers/'
Исправлено.

2023-08-24 15:54 UTC, olegtsss commented on src/backend/api/tests/test_case.py
> +        cls.guest_client = Client()
Исправлено.

2023-08-24 16:23 UTC, olegtsss commented on src/backend/api/tests/test_case.py
> +    ANSWER_5 = {'number': 1}
Сделано.

2023-08-24 16:24 UTC, olegtsss commented on src/backend/api/tests/test_urls.py
> +        self.assertEqual(response.data['content'], self.ANSWER_2['content'])
Сделано.

2023-08-25 17:17 UTC, TomatoInOil approved these changes

2023-08-25 17:18 UTC, merged