Send a message about the beginning of each stage
Studio-Yandex-Practicum/you_can_bot pull request #137
Opened 2024-03-26 17:03 UTC by faQfriend

Отправка сообщения пользователю о начале каждого этапа (нового круга задания).
Сокращение количества if в коде, меньшее ветвление.

2024-04-05 06:04 UTC, TomatoInOil requested changes

2024-04-05 06:04 UTC, TomatoInOil commented on src/bot/conversations/task_8/callback_funcs.py
> +    picked_choice = await _validate_callback_data(update)
Ещё я бы переименовал функции
```Python
_handle_first_stage_answer
_handle_second_stage_answer
_handle_third_stage_answer
```
В 
```Python
_save_first_stage_answer_to_context
_save_second_stage_answer_to_context
_save_third_stage_answer_to_context
```
Потому что их названия слишком похожи на `handle_answer_on_stage_n` и не отражают то, что совершают на самом деле

2024-04-06 10:32 UTC, faQfriend commented on src/bot/conversations/task_8/callback_funcs.py
> +    picked_choice = await _validate_callback_data(update)
Добавлен декоратор, функции переименованы.

2024-04-07 09:06 UTC, TomatoInOil approved these changes

2024-04-07 09:06 UTC, merged