Добавлена отправка сообщения Ментору в момент завершения задания Пользователем.
Studio-Yandex-Practicum/you_can_bot pull request #138
Opened 2024-03-28 16:42 UTC by faQfriend

Добавлена отправка сообщения ментору в момент завершения задания Пользователем.
Если ментор не назначен, отправка осуществляется старшему ментору.

2024-04-04 13:19 UTC, TomatoInOil requested changes
Проблема

2024-04-04 13:19 UTC, TomatoInOil commented on src/backend/api/conversation_utils.py
> +        await bot.send_message(chat_id=user_id, text=text, parse_mode=ParseMode.HTML)
Эти функции одинаковы, вместо task_completed_send_message можно использовать non_context_send_message

2024-04-04 13:19 UTC, TomatoInOil commented on src/backend/api/views/answer.py
Проблема с тестами, которая у тебя возникла решается мокированием функции, которая отправляет сообщения в telegram. В `src/backend/api/tests/test_answer/test_views.py` в нескольких тестах запрос отправляется с последним ответом на задание: `test_view_tasks_status_is_done`, `test_view_create_result_status_task_1`, `test_view_create_result_status_task_2`, `test_view_create_result_status_task_3`, `test_view_create_result_status_task_4`
Для них можно будет использовать `@patch`, чтобы не отправлять реальное сообщение в telegram при тестах 
```Python
@patch("api.views.answer.non_context_send_message")
def test_view_create_result_status_task_1(self, _mock_send_message):
```
Такое уже используется в проекте:
https://github.com/Studio-Yandex-Practicum/you_can_bot/blob/ae9f6317bce94833164b203bb9d82d1ad60e5139/src/backend/api/tests/test_problem/test_problems.py#L37-L38
Там также проверяется, что функция вызывается с ожидаемыми аргументами
https://github.com/Studio-Yandex-Practicum/you_can_bot/blob/ae9f6317bce94833164b203bb9d82d1ad60e5139/src/backend/api/tests/test_problem/test_problems.py#L61-L70

2024-04-04 13:24 UTC, TomatoInOil commented on src/backend/api/conversation_utils.py
> +        await bot.send_message(chat_id=user_id, text=text, parse_mode=ParseMode.HTML)
И устанавливать local_mode в True в нашем случае не нужно 
https://docs.python-telegram-bot.org/en/stable/telegram.bot.html#telegram.Bot.params.local_mode

2024-04-06 09:24 UTC, faQfriend commented on src/backend/api/conversation_utils.py
> +        await bot.send_message(chat_id=user_id, text=text, parse_mode=ParseMode.HTML)
Функция упразднена.

2024-04-06 09:32 UTC, faQfriend commented on src/backend/api/views/answer.py
Добавлены декораторы @patch для успешного прохождения Django-тестов.

2024-04-07 08:44 UTC, TomatoInOil approved these changes

2024-04-07 08:44 UTC, merged