Add function to calculate first task answers
Studio-Yandex-Practicum/you_can_bot pull request #16
Opened 2023-08-23 19:20 UTC by melax08

Добавил функцию для вычисления расшифровки по ответам по первому заданию. Добавил тесты для данного функционала.

Возникло несколько вопросов:
1. При тестах, насколько принципиально добавлять в базу данных тестовые данные, или достаточно создать экземпляры класса модели с нужными для теста данными и использовать их в тестах?
2. Достаточно ли тестов, или можно подумать над дополнительными. 
3. Нужно ли в функции расшифровки добавлять обработку особых случаев, например если в Answer.content длина строки != 6 символов (то есть консистентность данных нарушена)? Если да, то что делать при такой обработке особого случая? (просто логировать, прерывать выполнение функции, выкидывать какое-то исключение?).

2023-08-25 17:52 UTC, TomatoInOil requested changes
Отвечаю на твои вопросы
1. Думаю, что в этом случае достаточно создать экземпляры модели. 
2. Да, для логики, которая будет изложена в пункте 3
3. Да, было бы замечательно обрабатывать это исключение. А ещё могут быть случаи, когда несколько букв имеют одинаковые суммы баллов и там есть определённое поведение, обсужденное с заказчиком. Пришлю подробности в пачке.

2023-08-25 17:52 UTC, TomatoInOil commented on src/backend/api/calculation_service/task_1.py
> +        answer_points = list(map(int, answer.content))
Вместо list() можно использовать tuple(), т.к. нам не нужно его изменять

2023-08-25 17:52 UTC, TomatoInOil commented on src/backend/api/calculation_service/task_1.py
> +        ]
Тяжело читается, есть более лаконичный способ это сделать
```Python
        for index, value in enumerate(answer_points):
            points[index] += value
```

2023-08-25 17:52 UTC, TomatoInOil commented on src/backend/api/calculation_service/task_1.py
> +    results = sorted(zip(points, LETTERS))[::-1]
У `sorted()` есть аргумент `reverse=True`, который может заменить `[::-1]`

2023-08-26 10:13 UTC, melax08 commented on src/backend/api/calculation_service/task_1.py
> +        answer_points = list(map(int, answer.content))
Изменил.

2023-08-26 10:14 UTC, melax08 commented on src/backend/api/calculation_service/task_1.py
> +        ]
Согласен, сделал через enumerate.

2023-08-26 10:14 UTC, melax08 commented on src/backend/api/calculation_service/task_1.py
> +    results = sorted(zip(points, LETTERS))[::-1]
Точно! Заменил.

2023-08-26 13:58 UTC, TomatoInOil approved these changes

2023-08-26 13:59 UTC, merged