Add first conversation handler for acquaintance
Studio-Yandex-Practicum/you_can_bot pull request #2
Opened 2023-08-12 13:16 UTC by melax08

Добавил первый обработчик для команды /start, который выдает приветственное сообщение предлагает начать знакомство. За ним следует conversation handler, который служит для знакомства с пользователем.

Есть вопросы по:
1. Нужно ли обработчик для /start хранить в отдельном файле в папке bot, или он должен лежать в src/bot/conversations/general/
2. По файлам templates.py, нормальным ли образом они оформлены.
3. Вопрос по собираемой информации для отправки на API, на данный момент собрал только имя (которое вводит сам пользователь) и его chat_id в телеграмме, нужно ли что-то еще?

2023-08-14 13:46 UTC, TomatoInOil requested changes

2023-08-14 13:46 UTC, TomatoInOil commented on src/bot/conversations/general/acquaintance.py
> +    entry_points=[MessageHandler(filters.Regex('ПРИВЕТ'), start_acquaintance)],
Думаю лучше начинать общение с команды /start, которую telegram принуждает отправить в качестве первого сообщения, если ты боту пишешь впервые

2023-08-14 13:46 UTC, TomatoInOil commented on src/bot/conversations/general/templates.py
> +"""
При использовании `""" """` переносы строк учитываются, т.е. вот здесь
```Python
- Скилсет 3. Сделай выбор и действуй – с помощью специальной матрицы ты сам 
сделаешь свой профессиональный выбор и составишь образовательный маршрут.
```
Мы имеем перенос строки в сообщении после слова "сам"
![image](https://github.com/Studio-Yandex-Practicum/you_can_bot/assets/93451214/3e774121-adaa-485d-bbb1-1f1818e32e3b)
Чтобы этого избежать можно использовать `\` или не использовать `""" """`
```Python
- Скилсет 3. Сделай выбор и действуй – с помощью специальной матрицы ты сам \
сделаешь свой профессиональный выбор и составишь образовательный маршрут.
```
Кстати, по этой же причине в начале получился большой интервал 
![image](https://github.com/Studio-Yandex-Practicum/you_can_bot/assets/93451214/3e43ab5c-f151-42a1-a101-bfb34c601f6e)

2023-08-14 15:34 UTC, melax08 commented on src/bot/conversations/general/acquaintance.py
> +    context.user_data["user_title_name"] = user_name
Что подразумевается под ожидаемым ответом и какие критерии проверки?

Я так понимаю, пользователь должен строго предоставить свое имя и фамилию, разделяя пробелом, как на скриншоте: Иван Иванов. 

Что мне пришло в голову:
1. Из ответа пользователя на вопрос "Как тебя зовут", вытащить данные сообщения;
2. Применить к этим данным метод .title() (чтобы имя и фамилия были всегда строго с большой буквы);
3. Разбить с помощью split() данные;
4. Если размер полученного массива меньше != 2, вернуть пользователя к повторному вводу имени и фамилии;
5. Проверить регуляркой введенные данные, чтобы имя и фамилия содержали только символы А-Яа-я (либо в том числе и латиницу).

2023-08-14 15:40 UTC, melax08 commented on src/bot/conversations/general/acquaintance.py
> +    entry_points=[MessageHandler(filters.Regex('ПРИВЕТ'), start_acquaintance)],
Не совсем согласен. Сейчас при старте бота выдается сообщение в соответствии с фич листом: 

"Привет, дорогой друг! Спасибо, что выбрал проект YOU CAN! Ближайшее время мы проведем вместе. Надеемся, что оно будет интересным и продуктивным для тебя. С нами ты определишь свои сильные стороны и выберешь профессию, которая поможет их раскрыть"

Под этим сообщением выводится кнопка "ПРИВЕТ", которая и приводит к началу conversation знакомства. 

Или ты предлагаешь переместить тот текст, который я скинул выше, в описание бота, когда к нему переходишь, там где еще предлагается нажатие кнопки "/start" у бота, и чтобы диалог о знакомстве начинался сразу после /start?

2023-08-14 16:05 UTC, TomatoInOil commented on src/bot/conversations/general/acquaintance.py
> +    entry_points=[MessageHandler(filters.Regex('ПРИВЕТ'), start_acquaintance)],
Я просто про то, что в твоем случае, если без /start написать ПРИВЕТ в любой момент времени, то начнётся знакомство 
А вот если мы обработку кнопки ПРИВЕТ поместим в states из entry point, а в качестве точки входа сделаем /start и соответствующее первое сообщение, то такого не будет
Потом мы добавим проверку, когда сделаем API, что пользователь уже знаком и при повторном использовании /start будем выводить другое сообщение без кнопки ПРИВЕТ, чтобы не возникло исключений

2023-08-14 16:15 UTC, melax08 commented on src/bot/conversations/general/acquaintance.py
> +    entry_points=[MessageHandler(filters.Regex('ПРИВЕТ'), start_acquaintance)],
Понял, хорошо.

2023-08-16 08:09 UTC, TomatoInOil approved these changes

2023-08-16 08:19 UTC, merged