Feature/conversations task 2
Studio-Yandex-Practicum/you_can_bot pull request #6
Opened 2023-08-14 11:10 UTC by olegtsss

Подготовил хендлер для второго задания (вопросы с 18 по 87). В тестовом режиме подключил логи, потом удалю.

2023-08-14 14:59 UTC, TomatoInOil requested changes

2023-08-14 14:59 UTC, TomatoInOil commented on src/bot/conversations/task_2/conversation_handler.py
> +    return QUESTION_20
Эти функции очень похожи, а ещё впереди где-то 68 таких же функций. У меня даже подвис браузер. Это было бы уместно, если бы для каждой функции у нас был бы уникальный хэндлер, но на самом деле у нас один единственный `MessageHandler(filters.Regex("^(а|б)$"), callback_func)`, поэтому предлагаю отрефакторить код, совместив все эти функции в одну. 
Не проверял, но вот тебе идея: использовать user_data для хранения номера последнего вопроса.  
```Python
QUESTIONS = (QUESTION_1_TEXT, QUESTION_2_TEXT, QUESTION_3_TEXT, QUESTION_4_TEXT, ...)

QUESTION_STATE = "QUESTION_STATE"
RESULT_STATE = "RESULT_STATE"


async def show_question(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> str:
    last_question = context.user_data.get("last_question", 0)
    logger.info(ANSWER, update.message.from_user.username, 20, update.message.text)
    message_text = QUESTIONS[last_question]
    await update.message.reply_text(
        message_text,
        reply_markup=ReplyKeyboardMarkup(
            REPLY_KEYBOARD,
            one_time_keyboard=True,
            resize_keyboard=True,
            input_field_placeholder=INPUT_PLACEHOLDER,
        ),
    )
    last_question += 1
    if last_question == 70:
        context.user_data.clear()
        return RESULT_STATE
    context.user_data["last_question"] = last_question + 1
    return QUESTION_STATE


async def show_result(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> int:
    """Расшифровка."""
    logger.info(ANSWER, update.message.from_user.username, 70, update.message.text)
    await context.bot.send_message(
        chat_id=update.effective_chat.id, text=RESULT_TEXT
        # + Кнопка – Задание 3
    )
    return ConversationHandler.END


acquaintance_handler = ConversationHandler(
    entry_points=[MessageHandler(filters.Regex("Задание 2"), show_task_description)],
    states={
        QUESTION_STATE: [MessageHandler(filters.Regex("^(а|б)$"), show_question)],
        RESULT_STATE: [MessageHandler(filters.Regex("^(а|б)$"), show_result)],
    },
    fallbacks=[CommandHandler(CANCEL_COMMAND, cancel)],
)

```

2023-08-14 14:59 UTC, TomatoInOil commented on src/bot/conversations/task_2/conversation_handler.py
Аналогично
https://github.com/Studio-Yandex-Practicum/you_can_bot/pull/2#discussion_r1293411202

2023-08-14 16:38 UTC, olegtsss commented on .gitignore
> +test3.py
Сделано!

2023-08-14 16:39 UTC, olegtsss commented on .gitignore
> +.gitignore
Сделано!

2023-08-14 16:40 UTC, olegtsss commented on src/bot/conversations/task_2/conversation_handler.py
> +acquaintance_handler = ConversationHandler(
Сделано!

2023-08-15 11:41 UTC, olegtsss commented on src/bot/conversations/task_2/conversation_handler.py
> +    return QUESTION_20
Исправлено!

2023-08-16 09:46 UTC, TomatoInOil approved these changes

2023-08-16 09:47 UTC, merged