Keyboards fixes
Studio-Yandex-Practicum/you_can_bot pull request #66
Opened 2023-10-09 19:17 UTC by SG-Mash

Исправлены переходы на второе и третье задания.
Кнопки ответов во втором задании располагаются в одну строку в две колонки.

2023-10-09 20:28 UTC, TomatoInOil requested changes
Есть одна мелочь, которую нужно поправить перед слиянием

2023-10-09 20:28 UTC, TomatoInOil commented on src/bot/conversations/task_1/keyboards.py
>      return InlineKeyboardMarkup([keyboard])
Дебажный print() остался

2023-10-09 20:28 UTC, TomatoInOil commented on src/bot/conversations/task_2/keyboards.py
>  )
Можно улучшить читаемость кода с помощью шортката `InlineKeyboardMarkup.from_row()`
Этот и другие можно найти в документации
https://docs.python-telegram-bot.org/en/stable/telegram.inlinekeyboardmarkup.html#telegram.InlineKeyboardMarkup.from_button

2023-10-10 05:32 UTC, SG-Mash commented on src/bot/conversations/task_2/keyboards.py
>  )
Улучшено :)

2023-10-10 05:32 UTC, SG-Mash commented on src/bot/conversations/task_1/keyboards.py
>      return InlineKeyboardMarkup([keyboard])
Исправлено

2023-10-10 06:37 UTC, SG-Mash commented on src/bot/conversations/task_1/keyboards.py
>      return InlineKeyboardMarkup([keyboard])
Действительно, какой-то косяк случился с коммитом и пушем. Сделал новый коммит `Kb fixes`

2023-10-10 06:52 UTC, TomatoInOil approved these changes

2023-10-10 06:53 UTC, merged