add main menu and its sub-menus (buttons, keyboards, handlers)
Studio-Yandex-Practicum/you_can_bot pull request #7
Opened 2023-08-14 16:16 UTC by MarinaChernykh

Даниил, привет!
Выполнила таску по созданию главного меню.

Сделано:
- кнопка menu с командами (постоянная кнопка-гамбургер в левом нижнем углу)
- подменю главного меню (inline-кнопки)
- хендлеры ко всем этим кнопкам

TODO:
- в хендлере с инфо о профиле есть поля об имене и кол-ве пройденных заданий. Пока поставила имя из апдейта + константу вместо кол-ва заданий -> изменить, когда будет база (в коде есть TODO коммент)
- в хендлерах с изменением имя в профиле и с отправкой вопроса специалисту также оставила коммент, что там нужно будет сохранение данных в базу данных, когда она появится
- в нижней части файла с хендлерами я прописала, но закомментила множество CallbackQueryHandler'ов - они связывают инлайн-кнопки меню со списком задач / результатов по задачам (входные точки в ConversationHandlers по таскам, связанным с обработкой заданий) - пригодятся при объединении кусочков :)

2023-08-17 12:18 UTC, TomatoInOil requested changes

2023-08-17 12:18 UTC, TomatoInOil commented on src/bot/bot.py
Хендлеры не добавлены в create_bot()

2023-08-17 15:54 UTC, MarinaChernykh commented on src/bot/conversations/menu/keyboards.py
done!

2023-08-17 15:54 UTC, MarinaChernykh commented on src/bot/bot.py
> +    loop.run_until_complete(create_main_menu(Bot(os.getenv("TOKEN"))))
done!

2023-08-17 15:54 UTC, MarinaChernykh commented on src/bot/conversations/menu/handlers.py
> +) -> None:
done!

2023-08-18 09:12 UTC, TomatoInOil commented on src/bot/conversations/menu/handlers.py
> +        MessageHandler(filters.Regex('^Назад$'), move_back),
Ещё мне кажется, что эти две функции cancel и move_back выполняют одинаковые действия, но выводя разные сообщения. Если заменить текст в обоих случаях на "Действие отменено", а кнопку назвать "Отменить", то можно использовать только cancel и один handler 
Я это пишу потому, что сейчас кнопка "Назад" располагается на первом уровне глубины общения с пользователем, что по сути приводит к отмене выполнения отправленной команды, а не возвращению назад
Ситуация, когда кнопка "Назад" будет выполнять свою функцию располагается глубже в общении: когда мы смотрим расшифровки по заданиям и выбрали "Задание 1", прочитали, потом нажали "Назад", нас вернуло к выбору заданий и мы выбрали "Задание 2" и теперь читаем расшифровку по Заданию 2

2023-10-17 18:18 UTC, maks-pavlenkov commented
Доделал и переделал PR, который был до меня
Буду ждать критики)

2023-10-18 08:35 UTC, TomatoInOil requested changes
Хорошо, но есть, что поправить. В пачку напишу по оформлению сообщений.

2023-10-18 08:35 UTC, TomatoInOil commented on src/bot/utils/configs.py
> +EXTERNAL_REQUESTS_ARE_MOCK = os.getenv("EXTERNAL_REQUESTS_ARE_MOCK", True)
В таком случае, если написать True в переменных окружения, то выражение
`EXTERNAL_REQUESTS_ARE_MOCK is True`
Будет равно 
`False`
Потому что getenv читает это как строку `"True"`
Именно поэтому здесь было использовано `== "True"`

2023-10-18 08:35 UTC, TomatoInOil commented on src/bot/conversations/menu/callback_funcs.py
> +        print("Такого задания пока что нет")
Лишняя функция, попробуй её закомментировать, а также хендлер, который вызывает её внутри `show_all_tasks_handler`
И попробовать выбрать задание, которое не выполнено 
Всё будет работать, потому что в entry_point хендеров, которые отвечают за задания, указано прослушивание паттерна `r"^start_task_номер$"`
```Python
task_1_handler = ConversationHandler(
    entry_points=[
        MessageHandler(filters.Regex(FIRST_TASK_BUTTON_LABEL), start_task_1),
        CallbackQueryHandler(start_task_1, r"^start_task_1$"),
    ],
```

2023-10-18 08:35 UTC, TomatoInOil commented on src/bot/conversations/menu/decorators.py
> +            return ConversationHandler.END
Здесь важно обработать ситуацию, когда HTTPStatusError возникает из-за 404, чтобы отправить пользователю сообщение поясняющее, почему команда не выполнилась, например:
```Python
not_found_message = (
    "Я с тобой ещё не знаком, поэтому не могу выполнить для тебя эту команду."
    " Если хочешь познакомиться введи команду /start."
)
```
Подсказка:
```Python
from httpx import HTTPStatusError, codes

except HTTPStatusError as exception:
    if exception.response.status_code == codes.NOT_FOUND:
```

2023-10-18 08:35 UTC, TomatoInOil commented on src/bot/conversations/menu/callback_funcs.py
> +        )
Для этого есть константа ParseMode.HTML
https://docs.python-telegram-bot.org/en/latest/telegram.constants.html#telegram.constants.ParseMode

2023-10-18 08:35 UTC, TomatoInOil commented on src/bot/conversations/menu/handlers.py
> +            )
Т.к. в этот момент мы ожидаем, что пользователь напишет вопрос, то логичнее ждать обычное текстовое сообщение без
```
& ~filters.COMMAND
& ~filters.Regex("^(Подтвердить|Отменить)$")
```

2023-10-18 08:35 UTC, TomatoInOil commented on src/bot/conversations/menu/handlers.py
> +    update: Update, context: ContextTypes.DEFAULT_TYPE
Не используется, можно удалить, включая связанную константу INCORRECT_NAME

2023-10-18 08:35 UTC, TomatoInOil commented on src/bot/conversations/menu/handlers.py
> +    """Отменяет внесение изменений в профиль/ отправку вопроса специалисту."""
Функция переписана в cancel_save_question, поэтому не используется, можно удалить и связанную константу CANCEL_TEXT

2023-10-18 09:17 UTC, maks-pavlenkov commented on src/bot/conversations/menu/callback_funcs.py
> +        print("Такого задания пока что нет")
Так. Название функции у второго задания начинается с show....
То есть, нажимая на второе задание, вызовется start_task2, которой нет

Попросить привести переменные в консистентный вид?

2023-10-18 09:22 UTC, TomatoInOil commented on src/bot/conversations/menu/callback_funcs.py
> +        print("Такого задания пока что нет")
Для кнопок не имеет значения, как называется вызываемая функция, потому что callback_data сравнивается с pattern 
https://github.com/Studio-Yandex-Practicum/you_can_bot/blob/2b32b1e5387bbae7ffb61561b955defe956f75ba/src/bot/conversations/task_2/handlers.py#L26
Здесь он также соответствует `r"^start_task_номер$"`
То есть если у функции будет `callback_data="start_task_2"`
То будет вызывана функция `show_start_of_task_2`

2023-10-18 17:16 UTC, maks-pavlenkov commented on src/bot/conversations/menu/callback_funcs.py
> +        print("Такого задания пока что нет")
Точно, что-то не подумал!

2023-10-23 08:25 UTC, TomatoInOil approved these changes

2023-10-23 08:26 UTC, merged