Feature/django models
Studio-Yandex-Practicum/you_can_bot pull request #8
Opened 2023-08-15 09:48 UTC by olegtsss

Создал Джанго проект. Создал приложение api. Подготовил модели, насторил админку, отредактировал settings, выполнил миграции.

2023-08-16 08:03 UTC, TomatoInOil requested changes

2023-08-17 05:01 UTC, olegtsss commented on src/backend/backend/settings.py
> +if os.getenv('NEED_SQLITE'):
1. Не имеет значение задавать умолчательное значение False, так как если нет переменной среди переменных окружения, то и автоматически имеем False.
2. `if os.getenv('NEED_SQLITE')` даст нам `True`, если в `NEED_SQLITE` будет хоть что-то содержаться, например, `Давай работай`! Отсюда твое продположение верное. Отсюда достаточно моего решения, а твое решение избыточно и хрупкое, например, если зададут вместо `True` слово `Yes`.

2023-08-17 05:03 UTC, olegtsss commented on src/backend/backend/settings.py
> +MAX_LENGTH_SURNAME = 150
Сделано!

2023-08-17 05:07 UTC, olegtsss commented on src/backend/api/models.py
> +        return f'{self.message} {self.answer} {self.create_date}'
Исправлено!

2023-08-17 05:08 UTC, olegtsss commented on src/backend/api/models.py
> +    )
Исправлено!

2023-08-17 05:17 UTC, olegtsss commented on src/backend/api/models.py
> +    )
Исправлено.

2023-08-17 10:01 UTC, TomatoInOil commented on src/backend/backend/settings.py
> +if os.getenv('NEED_SQLITE'):
Найдутся и те, кто задаст `False`, т.к. переменную в любом случае нужно документировать в .env.example

2023-08-17 10:24 UTC, olegtsss commented on src/backend/api/models.py
> +    )
Переработано.

2023-08-17 10:25 UTC, olegtsss commented on src/backend/api/models.py
> +    )
Переработано

2023-08-17 10:25 UTC, olegtsss commented on src/backend/api/models.py
> +    )
Переработано

2023-08-17 12:22 UTC, TomatoInOil commented on src/backend/api/models.py
> +    # )
Да, определённо, мне казалось, что это поле уже есть, видимо, когда я редактировал схему, я случайно затёр это поле.

2023-08-17 16:12 UTC, olegtsss commented on src/backend/api/models.py
> +    # )
Сделано!

2023-08-18 15:47 UTC, TomatoInOil approved these changes

2023-08-18 15:48 UTC, merged