Feature/conversation task 1
Studio-Yandex-Practicum/you_can_bot pull request #9
Opened 2023-08-16 00:07 UTC by Serdron

2023-08-16 05:06 UTC, melax08 commented
<img width="482" alt="image" src="https://github.com/Studio-Yandex-Practicum/you_can_bot/assets/99960381/b4b24bcf-e035-40f4-901c-445f03c1aba2">

Длинное описание у кнопок не влезает в интерфейс телеграмма.

2023-08-16 12:42 UTC, Serdron commented
ReplyKeyboard тоже не вмещал весь текст и отображал только 4 ответа за раз, для остальных её надо было проматывать. Это точно было менее удобно.

2023-08-16 12:50 UTC, Serdron commented
В случае с а, б, в... Как лучше поступать с выбранными вариантами в сообщении? Удалять или помечать выбранными?

2023-08-17 10:24 UTC, TomatoInOil commented
Может выставлять баллы от 0 до 5 рядом с вариантами, когда пользователь нажимает на кнопки?

2023-08-23 11:05 UTC, Serdron commented
![IMG_20230823_140347.jpg](https://github.com/Studio-Yandex-Practicum/you_can_bot/assets/96815264/c95433be-dcea-4e19-91d9-70a252011033)

Телеграм не позволяет редактировать сообщения с клавиатурой. 
На данный момент вариант такой: после кнопки сообщение удаляется и высылается новое сообщение с обновленным текстом и кнопками. По завершению одного вопроса остаётся сообщение с баллами и появляется другое

2023-08-26 12:23 UTC, Serdron commented
Обновил

2023-08-31 17:31 UTC, TomatoInOil requested changes

2023-08-31 17:31 UTC, TomatoInOil commented on src/bot/conversations/task_1/handler.py
> +                f'*{template["text"]}*',
```Python
File "C:\dev\you_can_bot\src\bot\conversations\task_1\handler.py", line 189, in button
    await query.message.reply_text(
telegram.error.BadRequest: Can't parse entities: character '{' is reserved and must be escaped with the preceding '\'
```

2023-09-02 08:03 UTC, Serdron commented on src/bot/conversations/task_1/handler.py
> +PARSE_MODE = 'MarkdownV2'
готово

2023-09-02 08:03 UTC, Serdron commented on src/bot/conversations/task_1/handler.py
> +) -> InlineKeyboardMarkup:
готово

2023-09-02 08:03 UTC, Serdron commented on src/bot/conversations/task_1/handler.py
> +            first, second, third = get_result(query.from_user, context)
готово

2023-09-02 09:28 UTC, Serdron commented on src/bot/conversations/task_1/handler.py
> +                f'*{template["text"]}*',
исправил текст

2023-09-04 13:45 UTC, merged