удалена команда /profile из меню
Studio-Yandex-Practicum/you_can_bot pull request #94
Opened 2023-11-08 23:28 UTC by nikolaiborel

2023-11-11 09:59 UTC, TomatoInOil requested changes
Команда всё равно может быть обработана ботом, т.к. в проекте остались хендлеры и callback функции

2023-11-14 08:12 UTC, nikolaiborel commented
> Команда всё равно может быть обработана ботом, т.к. в проекте остались хендлеры и callback функции

То есть нужно полностью удалить эту команду из бота, а не только из меню? Просто я задачу буквально понял, удалить из меню, но про ее вызов вручную ничего не сказано

2023-11-14 10:50 UTC, TomatoInOil commented
> > Команда всё равно может быть обработана ботом, т.к. в проекте остались хендлеры и callback функции
> 
> То есть нужно полностью удалить эту команду из бота, а не только из меню? Просто я задачу буквально понял, удалить из меню, но про ее вызов вручную ничего не сказано

Да

2023-11-22 11:19 UTC, TomatoInOil approved these changes

2023-11-22 11:20 UTC, merged